-- ============================================================
-- CHEF NOOR CUISINE — FINAL PRODUCTION MIGRATION
-- Run once in Supabase SQL Editor.
-- This migration is additive: it does not delete existing orders,
-- subscriptions, menus or meals.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1) Site settings controlled from the admin panel
-- ------------------------------------------------------------
create table if not exists public.site_settings (
  id integer primary key default 1,
  slogan text not null default 'أكل البيت... بطابع براند عالمي',
  contact_phone text,
  whatsapp_phone text,
  instagram_url text,
  facebook_url text,
  hero_image_url text,
  circle_image_url text,
  story_image_url text,
  cta_image_url text,
  footer_meal_images jsonb not null default '[]'::jsonb,
  menu_publish_time time not null default '12:00',
  menu_stop_time time not null default '23:00',
  daily_delivery_fee numeric(10,2) not null default 1.00,
  timezone text not null default 'Asia/Amman',
  updated_at timestamptz not null default now(),
  constraint site_settings_singleton check (id = 1),
  constraint site_settings_delivery_nonnegative check (daily_delivery_fee >= 0),
  constraint site_settings_footer_images_array check (jsonb_typeof(footer_meal_images) = 'array')
);

insert into public.site_settings (id)
values (1)
on conflict (id) do nothing;

-- ------------------------------------------------------------
-- 2) Timestamp helper
-- ------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_settings_updated_at on public.site_settings;
create trigger site_settings_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 3) Admin helper — avoids recursive RLS checks on profiles
-- ------------------------------------------------------------
create or replace function public.is_chef_noor_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_chef_noor_admin() from public;
grant execute on function public.is_chef_noor_admin() to authenticated;

-- ------------------------------------------------------------
-- 4) Site settings RLS
-- Public can read website settings; only admin can change them.
-- ------------------------------------------------------------
alter table public.site_settings enable row level security;

drop policy if exists "site_settings_public_read" on public.site_settings;
create policy "site_settings_public_read"
on public.site_settings
for select
to anon, authenticated
using (true);

drop policy if exists "site_settings_admin_insert" on public.site_settings;
create policy "site_settings_admin_insert"
on public.site_settings
for insert
to authenticated
with check (public.is_chef_noor_admin());

drop policy if exists "site_settings_admin_update" on public.site_settings;
create policy "site_settings_admin_update"
on public.site_settings
for update
to authenticated
using (public.is_chef_noor_admin())
with check (public.is_chef_noor_admin());

-- ------------------------------------------------------------
-- 5) Required core tables (created only when absent)
-- ------------------------------------------------------------
create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  price numeric(10,2) default 3.00,
  active boolean default true,
  is_available boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.menu_months (
  id bigint generated by default as identity primary key,
  name text,
  year integer,
  month integer,
  start_date date,
  status text default 'draft',
  created_at timestamptz default now()
);

create table if not exists public.daily_menu (
  id bigint generated by default as identity primary key,
  month_id bigint,
  day_number integer,
  menu_date date not null,
  is_holiday boolean default false,
  is_published boolean default false,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.daily_menu_items (
  id bigint generated by default as identity primary key,
  daily_menu_id bigint not null,
  meal_id bigint not null,
  display_order integer default 1,
  available boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  customer_id uuid,
  plan_id integer,
  customer_name text,
  phone text,
  address text,
  plan_days integer,
  meals_per_day integer,
  price numeric(10,2),
  start_date date,
  end_date date,
  total_meals integer,
  used_meals integer default 0,
  remaining_meals integer,
  tracking_token text,
  status text default 'active',
  latitude double precision,
  longitude double precision,
  created_at timestamptz default now()
);

create table if not exists public.subscription_daily_meals (
  id bigint generated by default as identity primary key,
  subscription_id bigint not null,
  meal_id bigint,
  meal_name text,
  quantity integer default 1,
  meal_date date,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.daily_orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  phone text,
  address text,
  meal_name text,
  quantity integer default 1,
  order_date date default current_date,
  delivery_price numeric(10,2) default 1.00,
  total_price numeric(10,2),
  status text default 'pending',
  latitude double precision,
  longitude double precision,
  created_at timestamptz default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  customer_name text,
  rating integer default 5,
  message text,
  created_at timestamptz default now()
);

-- ------------------------------------------------------------
-- 6) Required columns used by the current application.
-- Add only if missing; existing data is preserved.
-- ------------------------------------------------------------

alter table public.meals
  add column if not exists description text,
  add column if not exists image_url text,
  add column if not exists price numeric(10,2) default 3.00,
  add column if not exists active boolean default true,
  add column if not exists is_available boolean default true;

alter table public.daily_orders
  add column if not exists customer_name text,
  add column if not exists phone text,
  add column if not exists address text,
  add column if not exists meal_name text,
  add column if not exists quantity integer default 1,
  add column if not exists order_date date default current_date,
  add column if not exists delivery_price numeric(10,2) default 1.00,
  add column if not exists total_price numeric(10,2),
  add column if not exists status text default 'pending',
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists created_at timestamptz default now();

alter table public.subscriptions
  add column if not exists customer_name text,
  add column if not exists phone text,
  add column if not exists address text,
  add column if not exists plan_id integer,
  add column if not exists plan_days integer,
  add column if not exists meals_per_day integer,
  add column if not exists price numeric(10,2),
  add column if not exists start_date date,
  add column if not exists end_date date,
  add column if not exists total_meals integer,
  add column if not exists used_meals integer default 0,
  add column if not exists remaining_meals integer,
  add column if not exists tracking_token text,
  add column if not exists status text default 'active',
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists created_at timestamptz default now();

alter table public.subscription_daily_meals
  add column if not exists subscription_id bigint,
  add column if not exists meal_id bigint,
  add column if not exists meal_name text,
  add column if not exists quantity integer default 1,
  add column if not exists meal_date date,
  add column if not exists notes text,
  add column if not exists created_at timestamptz default now();

alter table public.menu_months
  add column if not exists name text,
  add column if not exists year integer,
  add column if not exists month integer,
  add column if not exists start_date date,
  add column if not exists status text default 'draft',
  add column if not exists created_at timestamptz default now();

alter table public.daily_menu
  add column if not exists month_id bigint,
  add column if not exists day_number integer,
  add column if not exists menu_date date,
  add column if not exists is_holiday boolean default false,
  add column if not exists is_published boolean default false,
  add column if not exists notes text,
  add column if not exists created_at timestamptz default now();

alter table public.daily_menu_items
  add column if not exists daily_menu_id bigint,
  add column if not exists meal_id bigint,
  add column if not exists display_order integer default 1,
  add column if not exists available boolean default true,
  add column if not exists created_at timestamptz default now();

alter table public.feedback
  add column if not exists customer_name text,
  add column if not exists rating integer default 5,
  add column if not exists message text,
  add column if not exists created_at timestamptz default now();

-- ------------------------------------------------------------
-- 7) Safe indexes for production lookups
-- ------------------------------------------------------------
create index if not exists idx_daily_menu_date_published
  on public.daily_menu(menu_date, is_published);

create index if not exists idx_daily_menu_items_day_order
  on public.daily_menu_items(daily_menu_id, display_order);

create index if not exists idx_daily_orders_date_status
  on public.daily_orders(order_date, status);

create index if not exists idx_subscription_daily_meals_subscription_date
  on public.subscription_daily_meals(subscription_id, meal_date);

create unique index if not exists idx_subscriptions_tracking_token
  on public.subscriptions(tracking_token)
  where tracking_token is not null;

-- ------------------------------------------------------------
-- 8) Data sanity checks / repairs
-- ------------------------------------------------------------
update public.meals
set active = true
where active is null;

update public.meals
set is_available = true
where is_available is null;

update public.daily_orders
set quantity = 1
where quantity is null or quantity < 1;

update public.subscriptions
set used_meals = 0
where used_meals is null;

update public.subscriptions
set total_meals = coalesce(total_meals, plan_days * meals_per_day)
where total_meals is null
  and plan_days is not null
  and meals_per_day is not null;

update public.subscriptions
set remaining_meals = greatest(0, coalesce(total_meals, 0) - coalesce(used_meals, 0))
where remaining_meals is null;

-- ------------------------------------------------------------
-- 9) Production verification report
-- Run this SELECT after the migration.
-- ------------------------------------------------------------
select
  'site_settings' as table_name,
  exists(select 1 from information_schema.tables where table_schema='public' and table_name='site_settings') as exists;

select
  table_name,
  column_name,
  data_type
from information_schema.columns
where table_schema = 'public'
  and table_name in (
    'meals',
    'daily_orders',
    'subscriptions',
    'subscription_daily_meals',
    'menu_months',
    'daily_menu',
    'daily_menu_items',
    'feedback',
    'site_settings'
  )
order by table_name, ordinal_position;

select
  id,
  slogan,
  contact_phone,
  whatsapp_phone,
  instagram_url,
  facebook_url,
  menu_publish_time,
  menu_stop_time,
  daily_delivery_fee,
  timezone
from public.site_settings
where id = 1;

-- IMPORTANT:
-- 1) Do NOT auto-publish menu days when the planner creates them.
-- 2) Admin publishes the next working day manually.
-- 3) The website hides the next-day menu outside menu_publish_time/menu_stop_time.
-- 4) Thursday -> subscriber next working day is Saturday (Friday holiday).
-- 5) Friday -> subscriber next working day is Saturday.
-- 6) Daily orders keep their own order_date, so today's and tomorrow's
--    items can coexist in one cart without merging incorrectly.

-- ------------------------------------------------------------
-- 10) Required RPC verification
-- ------------------------------------------------------------
select
  routine_name,
  routine_schema,
  specific_name
from information_schema.routines
where routine_schema = 'public'
  and routine_name in ('create_menu_month', 'save_subscription_daily_meals')
order by routine_name;

-- If either RPC is missing, stop and restore/run your original
-- subscription/menu RPC SQL before deploying the frontend.

-- ============================================================
-- 11) MENU PRODUCTION RLS
-- Fixes admin save/publish failures when RLS is enabled on the
-- existing menu tables. Existing policies are not removed.
-- ============================================================

alter table public.menu_months enable row level security;
alter table public.daily_menu enable row level security;
alter table public.daily_menu_items enable row level security;

-- Admin can fully manage menu planning data.
drop policy if exists "menu_months_admin_all" on public.menu_months;
create policy "menu_months_admin_all"
on public.menu_months
for all
to authenticated
using (public.is_chef_noor_admin())
with check (public.is_chef_noor_admin());

drop policy if exists "daily_menu_admin_all" on public.daily_menu;
create policy "daily_menu_admin_all"
on public.daily_menu
for all
to authenticated
using (public.is_chef_noor_admin())
with check (public.is_chef_noor_admin());

drop policy if exists "daily_menu_items_admin_all" on public.daily_menu_items;
create policy "daily_menu_items_admin_all"
on public.daily_menu_items
for all
to authenticated
using (public.is_chef_noor_admin())
with check (public.is_chef_noor_admin());

-- Public website may only see published days.
drop policy if exists "daily_menu_public_published_read" on public.daily_menu;
create policy "daily_menu_public_published_read"
on public.daily_menu
for select
to anon, authenticated
using (is_published = true);

-- Public website may only see items belonging to a published day.
drop policy if exists "daily_menu_items_public_published_read" on public.daily_menu_items;
create policy "daily_menu_items_public_published_read"
on public.daily_menu_items
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.daily_menu dm
    where dm.id = daily_menu_items.daily_menu_id
      and dm.is_published = true
  )
);

-- Public meal data required to render published menus.
alter table public.meals enable row level security;
drop policy if exists "meals_public_active_read" on public.meals;
create policy "meals_public_active_read"
on public.meals
for select
to anon, authenticated
using (active = true and is_available = true);

drop policy if exists "meals_admin_all" on public.meals;
create policy "meals_admin_all"
on public.meals
for all
to authenticated
using (public.is_chef_noor_admin())
with check (public.is_chef_noor_admin());

-- Production verification: this should return true after the admin
-- publishes a day from the dashboard.
select id, menu_date, is_published
from public.daily_menu
order by menu_date desc
limit 10;

-- ============================================================
-- 12) DELIVERY DISPATCH V4
-- ============================================================
alter table public.subscription_daily_meals
  add column if not exists delivery_status text default 'pending';

alter table public.subscriptions
  add column if not exists tracking_token text;

alter table public.daily_orders
  add column if not exists tracking_token text;

create table if not exists public.delivery_routes (
  id bigint generated by default as identity primary key,
  route_date date not null unique,
  driver_id uuid references auth.users(id) on delete set null,
  status text not null default 'active',
  total_stops integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.delivery_stops (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.delivery_routes(id) on delete cascade,
  stop_order integer not null,
  source_type text not null check (source_type in ('subscription','order')),
  source_id bigint not null,
  customer_name text,
  phone text,
  address text,
  latitude double precision,
  longitude double precision,
  status text not null default 'pending',
  eta_minutes integer,
  arrived_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.driver_locations (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references auth.users(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  recorded_at timestamptz not null default now()
);

create index if not exists idx_delivery_stops_route_order on public.delivery_stops(route_id, stop_order);
create index if not exists idx_delivery_stops_source on public.delivery_stops(source_type, source_id);
create index if not exists idx_driver_locations_driver_time on public.driver_locations(driver_id, recorded_at desc);

create or replace function public.delivery_is_staff()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('admin','driver')
  );
$$;

drop policy if exists "delivery_routes_staff_all" on public.delivery_routes;
create policy "delivery_routes_staff_all" on public.delivery_routes
for all to authenticated using (public.delivery_is_staff()) with check (public.delivery_is_staff());

drop policy if exists "delivery_stops_staff_all" on public.delivery_stops;
create policy "delivery_stops_staff_all" on public.delivery_stops
for all to authenticated using (public.delivery_is_staff()) with check (public.delivery_is_staff());

drop policy if exists "driver_locations_staff_all" on public.driver_locations;
create policy "driver_locations_staff_all" on public.driver_locations
for all to authenticated using (public.delivery_is_staff()) with check (public.delivery_is_staff());

alter table public.delivery_routes enable row level security;
alter table public.delivery_stops enable row level security;
alter table public.driver_locations enable row level security;

-- Tracking view: intentionally exposes no customer identity/address.
create or replace function public.get_delivery_tracking(p_route_id bigint)
returns table(status text, stop_number integer, eta_minutes integer, driver_latitude double precision, driver_longitude double precision, delivered_stops integer, total_stops integer)
language sql stable security definer set search_path = public
as $$
  with r as (select * from public.delivery_routes where id = p_route_id),
  last_location as (
    select dl.latitude, dl.longitude from public.driver_locations dl join r on r.driver_id=dl.driver_id order by dl.recorded_at desc limit 1
  )
  select coalesce((select ds.status from public.delivery_stops ds where ds.route_id=p_route_id and ds.status <> 'delivered' order by ds.stop_order limit 1),'delivered'),
         coalesce((select ds.stop_order from public.delivery_stops ds where ds.route_id=p_route_id and ds.status <> 'delivered' order by ds.stop_order limit 1),0),
         (select ds.eta_minutes from public.delivery_stops ds where ds.route_id=p_route_id and ds.status <> 'delivered' order by ds.stop_order limit 1),
         (select latitude from last_location),(select longitude from last_location),
         (select count(*)::integer from public.delivery_stops where route_id=p_route_id and status='delivered'),
         (select total_stops from r);
$$;

-- Keep updated_at current.
drop trigger if exists delivery_routes_updated_at on public.delivery_routes;
create trigger delivery_routes_updated_at before update on public.delivery_routes for each row execute function public.set_updated_at();
drop trigger if exists delivery_stops_updated_at on public.delivery_stops;
create trigger delivery_stops_updated_at before update on public.delivery_stops for each row execute function public.set_updated_at();


alter table public.delivery_routes add column if not exists route_source text default 'smart';

-- ============================================================
-- PRODUCTION HARDENING — 2026-09-18
-- ============================================================
-- One menu row per date. Run only after duplicate menu_date rows
-- have been cleaned (as done in the current database).
create unique index if not exists ux_daily_menu_menu_date
  on public.daily_menu(menu_date);

-- Required customer location fields for delivery routing.
alter table public.subscriptions
  add column if not exists latitude double precision,
  add column if not exists longitude double precision;

alter table public.daily_orders
  add column if not exists latitude double precision,
  add column if not exists longitude double precision;

-- Delivery tables required by the Dispatch screen.
create table if not exists public.delivery_routes (
  id bigint generated by default as identity primary key,
  route_date date not null unique,
  driver_id uuid references auth.users(id) on delete set null,
  status text not null default 'active',
  total_stops integer not null default 0,
  route_source text not null default 'smart',
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.delivery_stops (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.delivery_routes(id) on delete cascade,
  stop_order integer not null,
  source_type text not null check (source_type in ('subscription','order')),
  source_id bigint not null,
  customer_name text,
  phone text,
  address text,
  latitude double precision,
  longitude double precision,
  status text not null default 'pending',
  eta_minutes integer,
  arrived_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.driver_locations (
  id bigint generated by default as identity primary key,
  driver_id uuid not null references auth.users(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  recorded_at timestamptz not null default now()
);

alter table public.delivery_routes enable row level security;
alter table public.delivery_stops enable row level security;
alter table public.driver_locations enable row level security;

create or replace function public.delivery_is_staff()
returns boolean language sql stable security definer set search_path=public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('admin','driver')
  );
$$;

grant execute on function public.delivery_is_staff() to authenticated;
